### ISSUE TITLE
Crash after choosing a side

### ISSUE THREAD

**Issue by MOON-E** [mpt1/netrunner_arena#3]
The program crashes after I click on corp or runner.

The command window tells me "Assertion failed: deck.size() > 0 && "Cannot draw from empty deck.", file main.cpp, line 115"

This happens regardless of what other settings I click beforehand.

**Comment by mp-t** [comment]
Most likely scenario: you copied an executable from a build later than 453 over an existing installation from an earlier build. The NRDB API changed, so existing data files are not compatible.

Try running the newest build found here https://github.com/mpt1/netrunner_arena/releases
in a clean directory.

**Comment by MOON-E** [comment]
The build I found works, but re-downloads all images on every run.

**Comment by mp-t** [comment]
I cannot reproduce that. It might try to download not yet available images every run. I have disabled that behavior in the new build 459.
But once you get a '200' return code the image should stay in the 'img' folder and never be downloaded again. Are you sure it is downloading **all previous downloaded** images again?
